id: PE055BA01
initial_creation_type: input
source_metadata:
  title: Padmasambhava
  language: en
  description: 'Texts by and about Guru Padmasambhava or Padmākara (padma ''byung
    gnas), the "Lotus-Born", who is credited with establishing Buddhism in Tibet:'
  volume:
    67efd64acc2b49b18d00329e14389e31:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    98a46f14ec504e31bc98679bf51265a2:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    0c5e2b08f1134181ad0ec5da8f90a48a:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    c8434186c6174fe09efc229cf1a56316:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    76dde76ea6f6454d94487af730fe0221:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      parent: Biography
    a2bb6b2a2cdc46b983533fb85006b464:
      title: A Praise to the Lotus King
      parent: Praise
    c59928e86b584cc6b86f78ac2b6d655d:
      title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
      parent: Praise
    c1750154e57444cc94f3d7e82cd2a12a:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Praise
    8638751b7dfb483db43b9c4c4ddb19f1:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Prayers
    02d1da9698684fea9d6dbc8c7d7be5bb:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Sang Offering
created_at: '2022-03-01T02:20:28.415482'
last_modified_at: '2022-03-01T02:20:28.415488'
